version: "3.9"

services:
  fastapi:
    build: ./fastapi_app
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - ./fastapi_app:/app
    restart: unless-stopped

  streamlit:
    build: ./streamlit_app
    container_name: streamlit_service
    ports:
      - "8501:8501"
    depends_on:
      - fastapi
    environment:
      - FASTAPI_URL=http://fastapi_service:8000/detect
    volumes:
      - ./streamlit_app:/app
    restart: unless-stopped
